import type { Game } from './mock-data'

// Curated homepage collection panels (e.g. "Football Fever"). Kept SEPARATE from the
// auto-generated mock-data.ts (regenerated by design-source/gen-mockdata.js) so a regen
// can't wipe it. Game art = the real now.gg CDN icons, downloaded to
// /public/games/football/ (512² PNGs). Titles/ratings scraped 1:1 from the live panel.
export const FOOTBALL_FEVER: Game[] = [
  { id: 'ea-sports-fc-mobile-24', title: 'EA SPORTS FC™ MOBILE 24 SOCCER', rating: 4.3, icon: '/games/football/ea-sports-fc-mobile-24.png', genre: 'Sports' },
  { id: 'smart-soccer', title: 'Smart Soccer', rating: 4.5, icon: '/games/football/smart-soccer.png', genre: 'Sports' },
  { id: 'efootball-2024', title: 'eFootball™ 2024', rating: 4.1, icon: '/games/football/efootball-2024.png', genre: 'Sports' },
  { id: 'retro-bowl', title: 'Retro Bowl', rating: 4.4, icon: '/games/football/retro-bowl.png', genre: 'Sports' },
  { id: 'football-brawl', title: 'FootBall Brawl', rating: 4.2, icon: '/games/football/football-brawl.png', genre: 'Sports' },
  { id: 'penalty-shooters-3', title: 'Penalty Shooters 3', rating: 4.3, icon: '/games/football/penalty-shooters-3.png', genre: 'Sports' },
  { id: 'football-cup-2024', title: 'Football Cup 2024', rating: 4.5, icon: '/games/football/football-cup-2024.png', genre: 'Sports' },
  { id: 'final-kick-football-legends', title: 'Final Kick Football Legends', rating: 4.8, icon: '/games/football/final-kick-football-legends.png', genre: 'Sports' },
  { id: 'football-hero', title: 'Football Hero', rating: 5.0, icon: '/games/football/football-hero.png', genre: 'Sports' },
  { id: 'penalty-kick', title: 'Penalty Kick', rating: 4.3, icon: '/games/football/penalty-kick.png', genre: 'Sports' },
  { id: 'football-heads', title: 'FootBall Heads', rating: 4.0, icon: '/games/football/football-heads.png', genre: 'Sports' },
]
